service: oz-tracker

# Name of the container image.
image: mishinator/oz-tracker

# Deploy to these servers.
servers:
  web:
    - oztracker-production.up.railway.app

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# Set ssl: false if using something like Cloudflare to terminate SSL (but keep host!).
proxy:
  ssl: true
  host: oztracker-production.up.railway.app

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: mishinator

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  DATABASE_URL: <%= ENV['DATABASE_URL'] %>
  PGDATABASE: <%= ENV['PGDATABASE'] %>
  PGUSER: <%= ENV['PGUSER'] %>
  PGPASSWORD: <%= ENV['PGPASSWORD'] %>
  PGHOST: <%= ENV['PGHOST'] %>
  PGPORT: <%= ENV['PGPORT'] %>
  REDIS_URL: <%= ENV['REDIS_URL'] %>
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
  RAILS_ENV: <%= ENV['RAILS_ENV'] %>
  secret:
    - RAILS_MASTER_KEY
